<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lixionggang-PC" name="192.168.56.101:5555" tests="3" failures="1" timestamp="25 Jun 2016 09:12:51 GMT" time="102.398" errors="0">
  <testcase name="login" time="23.797" classname="cn.crazy.appium.testcases.ZhihuTest"/>
  <testcase name="login" time="19.393" classname="cn.crazy.appium.testcases.ZhihuTest"/>
  <testcase name="reg" time="39.137" classname="cn.crazy.appium.testcases.ZhihuTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at cn.crazy.appium.testng.Assertion.fail(Assertion.java:63)
	at cn.crazy.appium.testng.Assertion.assertEquals(Assertion.java:19)
	at cn.crazy.appium.testcases.ZhihuTest.reg(ZhihuTest.java:75)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- reg -->
</testsuite> <!-- 192.168.56.101:5555 -->
