<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="127.0.0.1:62001"
           tests="5"
           failures="2"
           errors="0"
           skipped="3"
           time="107.382">
  <properties />
            <testcase name="login" time="53.954" classname="cn.crazy.appium.testcases.ZhihuTest0716">
                <failure type="java.lang.AssertionError"
                  message="登录用户名错误执行失败"
              >
<![CDATA[java.lang.AssertionError: 登录用户名错误执行失败
  org.testng.Assert.fail(Assert.java:94)
  cn.crazy.appium.testng.Assertion.fail(Assertion.java:80)
  cn.crazy.appium.testcases.ZhihuTest0716.login(ZhihuTest0716.java:65)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
            <testcase name="login" time="53.428" classname="cn.crazy.appium.testcases.ZhihuTest0716">
                <failure type="java.lang.AssertionError"
                  message="登录成功执行失败"
              >
<![CDATA[java.lang.AssertionError: 登录成功执行失败
  org.testng.Assert.fail(Assert.java:94)
  cn.crazy.appium.testng.Assertion.fail(Assertion.java:80)
  cn.crazy.appium.testcases.ZhihuTest0716.login(ZhihuTest0716.java:65)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
            <testcase name="addAnswer" time="0.0" classname="cn.crazy.appium.testcases.ZhihuTest0716">
          <skipped />
    </testcase>
            <testcase name="logout" time="0.0" classname="cn.crazy.appium.testcases.ZhihuTest0716">
          <skipped />
    </testcase>
            <testcase name="article" time="0.0" classname="cn.crazy.appium.testcases.ZhihuTest0716">
          <skipped />
    </testcase>
  
  
</testsuite>
